### ISSUE TITLE
Error Reports for Registration

### ISSUE THREAD

**Issue by ibyers** [zachsanchez113/tableau#19]
Implement error messages for the following situations:
--invalid username (email)
--invalid password (must include a special character, number, upper and lowercase and be 6-13 chars)
--username (email) confirmation does not match original
--password does not match original
--username(email) already in use

**Comment by zachsanchez113** [comment]
Blocked by API for network errors

Can still implement email validation, password validation

**Comment by zachsanchez113** [comment]
PR #104
