### ISSUE TITLE
Create new database entry when registering

### ISSUE THREAD

**Issue by ibyers** [zachsanchez113/tableau#29]
Check that the user does not already have an account
Create new document in the database

**Comment by zachsanchez113** [comment]
Moved to 'in-progress' because a draft schema was made and an initial writing of the corresponding code for DB connectivity/creation was written.

**Comment by zachsanchez113** [comment]
Assigned myself but I assume somebody else will have to hop on as well to send me the required data.

**Comment by zachsanchez113** [comment]
This is implemented but not functioning at the moment, the entry creation function is hanging. Debugging is currently underway.

**Comment by zachsanchez113** [comment]
PR #52

**Comment by zachsanchez113** [comment]
PR #52 approve by Ian
