### ISSUE TITLE
Send registration data to API as JSON

### ISSUE THREAD

**Issue by tcushman3** [zachsanchez113/tableau#37]
In order to register new users, we need to store the input text, and, after being checked for errors, POST it to the API in JSON format for processing.

**Comment by zachsanchez113** [comment]
Here's what being processed on the backend:

```
  var newUser = new userSchema({

    "email": request.body.email,
    "name": request.body.name,
    "pwd": request.body.pwd,
    "bday": request.body.bday,
    "rank": (request.body.rank == null) ? null : request.body.rank

  });
```
Make sure you enter all of the fields, with `rank` being optional.

**Comment by zachsanchez113** [comment]
return 200 and the hashed password if successful
return 400 if a required field is missing
else return 500 and the error
