### ISSUE TITLE
Send login data to database as JSON

### ISSUE THREAD

**Issue by tcushman3** [zachsanchez113/tableau#39]
After errors have been handled, we should send the login data to the database in order to check if that user exists in the database, and if the entered password is correct.

**Comment by zachsanchez113** [comment]
This hasn't been implemented as of 1/24, but should be relatively soon. You will just need to send the email to me and I'll return the email/password combo, validation will be on your end.

**Comment by zachsanchez113** [comment]
To provide login credentials to the API, for now just send the email and the password in a JSON object.

@return {undefined} 200 if passwords matched
 @return {undefined} 400 if no email was provided
 @return {undefined} 401 if incorrect password was provided
 @return {undefined} 500 if DB error was encountered
